import "../js/core/CurateFunctions/CurateFunctions.js";
import "../js/core/CustomPreservationConfigs.js";
import "../js/core/fileInfoModifier.js";
import "../js/core/MetadataHierarchies.js";
import "../js/core/OAIHarvestClient.js";
import "../js/core/publicAccessModifier.js";
import "../js/core/tourModifier.js";
import "../js/core/ChecksumValidation.js";
import "../js/core/PassOaiToChildren.js";
import "../js/core/consoleModifier.js";
import "../js/core/messageModifier.js";
import "../js/core/fixes/FixInfoPanelScroll.js";
import "../js/web-components/atom-search.js";
import "../js/web-components/atom-connector.js";
import "../js/web-components/dip-slug-resolver.js";
import "../js/web-components/contextual-help.js";
import "../js/web-components/oai-harvest-updates.js";
//import './deprecated/UploadChecksumGenerator.js';
import "../js/core/PermissionEnforcers.js";
import "../js/external/ExternalScripts.js";
//import 'chart.js';
//import Swal from 'sweetalert2';
//import Papa from 'papaparse';
//import he from 'he';
