import '../js/core/CurateFunctions.js';
import '../js/core/EnterpriseMetadataPanel_V2.js';
import '../js/core/fileInfoModifier.js';
import './workers/hashWorker.worker.js';
import '../js/core/OAIHarvestClient.js';
import '../js/core/publicAccessModifier.js';
import '../js/core/tourModifier.js';
import '../js/core/UploadChecksumGenerator.js';
import '../js/external/ExternalScripts.js';
import 'chart.js';
import Swal from 'sweetalert2';
import Papa from 'papaparse';
import he from 'he';